### ISSUE TITLE
Sometimes (content) iframe won't resize

### ISSUE THREAD

**Issue by dachinat** [zeroasterisk/react-iframe-resizer-super#8]
In my situation everything works fine from first glance, however sometimes iframe won't resize, then after clicking it will resize again.

I'm using `"iframe-resizer": "^3.6.1"` and `"react-iframe-resizer-super": "^0.2.0"`

My code for iframe is (I'm using _content-based_ iframe)

```
<IframeResizer
    src={null}
    content={activeMessage.htmlEdited}
    iframeResizerOptions={{checkOrigin: false, resizeFrom: 'parent', heightCalculationMethod: 'max'}}
    iframeResizerEnable={true}
    iframeResizerUrl="https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/3.5.8/iframeResizer.contentWindow.min.js">
</IframeResizer>
```

I am adding a small (20s) video for the demonstration:
[Watch video demonstration here](https://streamable.com/5pnqm)

Do you think there is a quick fix to this? Or anything I can do about this?
Thanks in advance!

**Comment by ShaileshInfyom** [comment]
https://github.com/davidjbradshaw/iframe-resizer/issues/870#issuecomment-702188337 see here for solution

**Comment by dachinat** [comment]
@ShaileshInfyom thanks a lot
